package libyara

const (
	ERROR_SUCCESS                        ErrNo = 0
	ERROR_INSUFFICIENT_MEMORY            ErrNo = 1
	ERROR_COULD_NOT_ATTACH_TO_PROCESS    ErrNo = 2
	ERROR_COULD_NOT_OPEN_FILE            ErrNo = 3
	ERROR_COULD_NOT_MAP_FILE             ErrNo = 4
	ERROR_INVALID_FILE                   ErrNo = 6
	ERROR_CORRUPT_FILE                   ErrNo = 7
	ERROR_UNSUPPORTED_FILE_VERSION       ErrNo = 8
	ERROR_INVALID_REGULAR_EXPRESSION     ErrNo = 9
	ERROR_INVALID_HEX_STRING             ErrNo = 10
	ERROR_SYNTAX_ERROR                   ErrNo = 11
	ERROR_LOOP_NESTING_LIMIT_EXCEEDED    ErrNo = 12
	ERROR_DUPLICATED_LOOP_IDENTIFIER     ErrNo = 13
	ERROR_DUPLICATED_IDENTIFIER          ErrNo = 14
	ERROR_DUPLICATED_TAG_IDENTIFIER      ErrNo = 15
	ERROR_DUPLICATED_META_IDENTIFIER     ErrNo = 16
	ERROR_DUPLICATED_STRING_IDENTIFIER   ErrNo = 17
	ERROR_UNREFERENCED_STRING            ErrNo = 18
	ERROR_UNDEFINED_STRING               ErrNo = 19
	ERROR_UNDEFINED_IDENTIFIER           ErrNo = 20
	ERROR_MISPLACED_ANONYMOUS_STRING     ErrNo = 21
	ERROR_INCLUDES_CIRCULAR_REFERENCE    ErrNo = 22
	ERROR_INCLUDE_DEPTH_EXCEEDED         ErrNo = 23
	ERROR_WRONG_TYPE                     ErrNo = 24
	ERROR_EXEC_STACK_OVERFLOW            ErrNo = 25
	ERROR_SCAN_TIMEOUT                   ErrNo = 26
	ERROR_TOO_MANY_SCAN_THREADS          ErrNo = 27
	ERROR_CALLBACK_ERROR                 ErrNo = 28
	ERROR_INVALID_ARGUMENT               ErrNo = 29
	ERROR_TOO_MANY_MATCHES               ErrNo = 30
	ERROR_INTERNAL_FATAL_ERROR           ErrNo = 31
	ERROR_NESTED_FOR_OF_LOOP             ErrNo = 32
	ERROR_INVALID_FIELD_NAME             ErrNo = 33
	ERROR_UNKNOWN_MODULE                 ErrNo = 34
	ERROR_NOT_A_STRUCTURE                ErrNo = 35
	ERROR_NOT_INDEXABLE                  ErrNo = 36
	ERROR_NOT_A_FUNCTION                 ErrNo = 37
	ERROR_INVALID_FORMAT                 ErrNo = 38
	ERROR_TOO_MANY_ARGUMENTS             ErrNo = 39
	ERROR_WRONG_ARGUMENTS                ErrNo = 40
	ERROR_WRONG_RETURN_TYPE              ErrNo = 41
	ERROR_DUPLICATED_STRUCTURE_MEMBER    ErrNo = 42
	ERROR_EMPTY_STRING                   ErrNo = 43
	ERROR_DIVISION_BY_ZERO               ErrNo = 44
	ERROR_REGULAR_EXPRESSION_TOO_LARGE   ErrNo = 45
	ERROR_TOO_MANY_RE_FIBERS             ErrNo = 46
	ERROR_COULD_NOT_READ_PROCESS_MEMORY  ErrNo = 47
	ERROR_INVALID_EXTERNAL_VARIABLE_TYPE ErrNo = 48
	ERROR_REGULAR_EXPRESSION_TOO_COMPLEX ErrNo = 49
	ERROR_INVALID_MODULE_NAME            ErrNo = 50
	ERROR_TOO_MANY_STRINGS               ErrNo = 51
	ERROR_INTEGER_OVERFLOW               ErrNo = 52
	ERROR_CALLBACK_REQUIRED              ErrNo = 53
	ERROR_INVALID_OPERAND                ErrNo = 54
	ERROR_COULD_NOT_READ_FILE            ErrNo = 55
	ERROR_DUPLICATED_EXTERNAL_VARIABLE   ErrNo = 56
	ERROR_INVALID_MODULE_DATA            ErrNo = 57
	ERROR_WRITING_FILE                   ErrNo = 58
	ERROR_INVALID_MODIFIER               ErrNo = 59
	ERROR_DUPLICATED_MODIFIER            ErrNo = 60
	ERROR_BLOCK_NOT_READY                ErrNo = 61
	ERROR_INVALID_PERCENTAGE             ErrNo = 62
	ERROR_IDENTIFIER_MATCHES_WILDCARD    ErrNo = 63
	ERROR_INVALID_VALUE                  ErrNo = 64
	ERROR_TOO_SLOW_SCANNING              ErrNo = 65
	ERROR_UNKNOWN_ESCAPE_SEQUENCE        ErrNo = 66
)

type ErrNo uint32

func (en ErrNo) String() string {
	switch en {
	case ERROR_SUCCESS:
		return "SUCCESS"
	case ERROR_INSUFFICIENT_MEMORY:
		return "ERROR_INSUFFICIENT_MEMORY"
	case ERROR_COULD_NOT_ATTACH_TO_PROCESS:
		return "ERROR_COULD_NOT_ATTACH_TO_PROCESS"
	case ERROR_COULD_NOT_OPEN_FILE:
		return "ERROR_COULD_NOT_OPEN_FILE"
	case ERROR_COULD_NOT_MAP_FILE:
		return "ERROR_COULD_NOT_MAP_FILE"
	case ERROR_INVALID_FILE:
		return "ERROR_INVALID_FILE"
	case ERROR_CORRUPT_FILE:
		return "ERROR_CORRUPT_FILE"
	case ERROR_UNSUPPORTED_FILE_VERSION:
		return "ERROR_UNSUPPORTED_FILE_VERSION"
	case ERROR_INVALID_REGULAR_EXPRESSION:
		return "ERROR_INVALID_REGULAR_EXPRESSION"
	case ERROR_INVALID_HEX_STRING:
		return "ERROR_INVALID_HEX_STRING"
	case ERROR_SYNTAX_ERROR:
		return "ERROR_SYNTAX_ERROR"
	case ERROR_LOOP_NESTING_LIMIT_EXCEEDED:
		return "ERROR_LOOP_NESTING_LIMIT_EXCEEDED"
	case ERROR_DUPLICATED_LOOP_IDENTIFIER:
		return "ERROR_DUPLICATED_LOOP_IDENTIFIER"
	case ERROR_DUPLICATED_IDENTIFIER:
		return "ERROR_DUPLICATED_IDENTIFIER"
	case ERROR_DUPLICATED_TAG_IDENTIFIER:
		return "ERROR_DUPLICATED_TAG_IDENTIFIER"
	case ERROR_DUPLICATED_META_IDENTIFIER:
		return "ERROR_DUPLICATED_META_IDENTIFIER"
	case ERROR_DUPLICATED_STRING_IDENTIFIER:
		return "ERROR_DUPLICATED_STRING_IDENTIFIER"
	case ERROR_UNREFERENCED_STRING:
		return "ERROR_UNREFERENCED_STRING"
	case ERROR_UNDEFINED_STRING:
		return "ERROR_UNDEFINED_STRING"
	case ERROR_UNDEFINED_IDENTIFIER:
		return "ERROR_UNDEFINED_IDENTIFIER"
	case ERROR_MISPLACED_ANONYMOUS_STRING:
		return "ERROR_MISPLACED_ANONYMOUS_STRING"
	case ERROR_INCLUDES_CIRCULAR_REFERENCE:
		return "ERROR_INCLUDES_CIRCULAR_REFERENCE"
	case ERROR_INCLUDE_DEPTH_EXCEEDED:
		return "ERROR_INCLUDE_DEPTH_EXCEEDED"
	case ERROR_WRONG_TYPE:
		return "ERROR_WRONG_TYPE"
	case ERROR_EXEC_STACK_OVERFLOW:
		return "ERROR_EXEC_STACK_OVERFLOW"
	case ERROR_SCAN_TIMEOUT:
		return "ERROR_SCAN_TIMEOUT"
	case ERROR_TOO_MANY_SCAN_THREADS:
		return "ERROR_TOO_MANY_SCAN_THREADS"
	case ERROR_CALLBACK_ERROR:
		return "ERROR_CALLBACK_ERROR"
	case ERROR_INVALID_ARGUMENT:
		return "ERROR_INVALID_ARGUMENT"
	case ERROR_TOO_MANY_MATCHES:
		return "ERROR_TOO_MANY_MATCHES"
	case ERROR_INTERNAL_FATAL_ERROR:
		return "ERROR_INTERNAL_FATAL_ERROR"
	case ERROR_NESTED_FOR_OF_LOOP:
		return "ERROR_NESTED_FOR_OF_LOOP"
	case ERROR_INVALID_FIELD_NAME:
		return "ERROR_INVALID_FIELD_NAME"
	case ERROR_UNKNOWN_MODULE:
		return "ERROR_UNKNOWN_MODULE"
	case ERROR_NOT_A_STRUCTURE:
		return "ERROR_NOT_A_STRUCTURE"
	case ERROR_NOT_INDEXABLE:
		return "ERROR_NOT_INDEXABLE"
	case ERROR_NOT_A_FUNCTION:
		return "ERROR_NOT_A_FUNCTION"
	case ERROR_INVALID_FORMAT:
		return "ERROR_INVALID_FORMAT"
	case ERROR_TOO_MANY_ARGUMENTS:
		return "ERROR_TOO_MANY_ARGUMENTS"
	case ERROR_WRONG_ARGUMENTS:
		return "ERROR_WRONG_ARGUMENTS"
	case ERROR_WRONG_RETURN_TYPE:
		return "ERROR_WRONG_RETURN_TYPE"
	case ERROR_DUPLICATED_STRUCTURE_MEMBER:
		return "ERROR_DUPLICATED_STRUCTURE_MEMBER"
	case ERROR_EMPTY_STRING:
		return "ERROR_EMPTY_STRING"
	case ERROR_DIVISION_BY_ZERO:
		return "ERROR_DIVISION_BY_ZERO"
	case ERROR_REGULAR_EXPRESSION_TOO_LARGE:
		return "ERROR_REGULAR_EXPRESSION_TOO_LARGE"
	case ERROR_TOO_MANY_RE_FIBERS:
		return "ERROR_TOO_MANY_RE_FIBERS"
	case ERROR_COULD_NOT_READ_PROCESS_MEMORY:
		return "ERROR_COULD_NOT_READ_PROCESS_MEMORY"
	case ERROR_INVALID_EXTERNAL_VARIABLE_TYPE:
		return "ERROR_INVALID_EXTERNAL_VARIABLE_TYPE"
	case ERROR_REGULAR_EXPRESSION_TOO_COMPLEX:
		return "ERROR_REGULAR_EXPRESSION_TOO_COMPLEX"
	case ERROR_INVALID_MODULE_NAME:
		return "ERROR_INVALID_MODULE_NAME"
	case ERROR_TOO_MANY_STRINGS:
		return "ERROR_TOO_MANY_STRINGS"
	case ERROR_INTEGER_OVERFLOW:
		return "ERROR_INTEGER_OVERFLOW"
	case ERROR_CALLBACK_REQUIRED:
		return "ERROR_CALLBACK_REQUIRED"
	case ERROR_INVALID_OPERAND:
		return "ERROR_INVALID_OPERAND"
	case ERROR_COULD_NOT_READ_FILE:
		return "ERROR_COULD_NOT_READ_FILE"
	case ERROR_DUPLICATED_EXTERNAL_VARIABLE:
		return "ERROR_DUPLICATED_EXTERNAL_VARIABLE"
	case ERROR_INVALID_MODULE_DATA:
		return "ERROR_INVALID_MODULE_DATA"
	case ERROR_WRITING_FILE:
		return "ERROR_WRITING_FILE"
	case ERROR_INVALID_MODIFIER:
		return "ERROR_INVALID_MODIFIER"
	case ERROR_DUPLICATED_MODIFIER:
		return "ERROR_DUPLICATED_MODIFIER"
	case ERROR_BLOCK_NOT_READY:
		return "ERROR_BLOCK_NOT_READY"
	case ERROR_INVALID_PERCENTAGE:
		return "ERROR_INVALID_PERCENTAGE"
	case ERROR_IDENTIFIER_MATCHES_WILDCARD:
		return "ERROR_IDENTIFIER_MATCHES_WILDCARD"
	case ERROR_INVALID_VALUE:
		return "ERROR_INVALID_VALUE"
	case ERROR_TOO_SLOW_SCANNING:
		return "ERROR_TOO_SLOW_SCANNING"
	case ERROR_UNKNOWN_ESCAPE_SEQUENCE:
		return "ERROR_UNKNOWN_ESCAPE_SEQUENCE"
	default:
		return "UNKNOWN_ERROR"
	}
}
